# Generated by Django 4.2.7 on 2023-11-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='icon_from',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
